catalog/urls.py
from django.urls import path
from django.conf.urls import url
from .import views

urlpatterns = [
    path('', views.product_list, name='product_list'),
    path('<category_slug>', views.product_list,
         name='product_list_by_category',
         ),
    path('<id><slug>', views.product_detail, name='product_detail'),






]

gamecity/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import RedirectView
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('catalog/', include('catalog.urls')),
    path('catalog/', include(('catalog.urls', 'catalog'), namespace='catalog')),
    path('', RedirectView.as_view(url='catalog/', permanent=True)),
    path('accounts/', include('django.contrib.auth.urls')),
]
urlpatterns += static(
    settings.STATIC_URL, document_root=settings.STATIC_ROOT)

if settings.DEBUG:

    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

catalog/models.py
from django.db import models
from django.urls import reverse
from django.contrib.auth.models import User
from datetime import date


class Category(models.Model):
    name = models.CharField(
        max_length=255, help_text='Enter a category here')
    slug = models.SlugField(max_length=255, db_index=True, unique=True)

    class Meta:
        ordering = ['name']
        verbose_name_plural = 'categories'

    def __str__(self):
        """String for representing the Model object."""
        return self.name

    def get_absolute_url(self):
        """Returns the url to access a detail record for this category."""
        # return reverse('category-detail', args=[str(self.id)])
        return reverse('catalog:product_list_by_category', args=[self.slug])


class Product(models.Model):
    """Model representing a product class."""
    category = models.ForeignKey(
        Category, on_delete=models.CASCADE, related_name='products')
    name = models.CharField(
        max_length=255, help_text='Enter a product name')
    slug = models.SlugField(max_length=255, db_index=True)
    image = models.ImageField(
        upload_to='products/%Y/%m/%d', blank=True)
    description = models.TextField(
        max_length=1000, blank=True, help_text='Enter a brief description of the product')
    price_in_shillings = models.DecimalField(max_digits=10, decimal_places=2)
    stock = models.PositiveIntegerField()
    available = models.BooleanField(default=True)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    condition = models.CharField(
        max_length=255, null=True, blank=True)
    customer = models.ForeignKey(
        User, on_delete=models.SET_NULL, null=True, blank=True)

    class Meta:
        ordering = ['name']
        # we define this index because we want to query products by both id and slug
        index_together = ('id', 'slug')
        verbose_name_plural = "products"

    @property
    def is_available(self):
        if self.available and date.today() > self.available:
            return True
        return False

    def __str__(self):
        """String for representing the Model object."""
        return self.name

    def get_absolute_url(self):
        """Returns the url to access a detail record for this electronic."""
        # return reverse('product-detail', args=[str(self.id)])
        return reverse('catalog:product_detail', args=[self.id, self.slug])

catalog/views.py
from django.shortcuts import render, get_object_or_404
from .models import Category, Product
from django.views import generic
from django.contrib.auth.decorators import login_required
from django.http import HttpResponse



def product_list(request, category_slug=None):
    category = None
    categories = Category.objects.all()
    products = Product.objects.filter(available=True)
    visits = request.session.get('visits', 1)
    request.session['visits'] = visits + 1
    if category_slug:
        category = get_object_or_404(Category, slug=category_slug)
        products = products.filter(category=category)
    return render(request,
                  'catalog/product/list.html',
                  {'category': category,
                   'categories': categories,
                   'products': products,
                   'visits': visits, })


def product_detail(request, id, slug):
    product = get_object_or_404(Product,
                                id=id,
                                slug=slug,
                                available=True)
    return render(request,
                  'catalog/product/detail.html',
                  {'product': product})

catalog/templates/catalog/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <title>{% block title %}GameCity Electronics{% endblock %}</title>
    {% comment %}
    <link href="{% static " css
    /base.css" %}" rel="stylesheet"> {% endcomment %}
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-BmbxuPwQa2lc/FVzBcNJ7UAyJxM6wuqIj61tLrc4wSX0szH/Ev+nYRRuWlolflfl" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'css/styles.css' %}">
</head>
<body style="background-color: #fff">
<div class="container-fluid">
    <div class="row">
        <div class="col-sm-2">
            {% block sidebar %}
            <ul class="sidebar-nav">
                <div id="header">
                    <a href="/" class="logo">GameCity Electronics</a>
                </div>
                {% if user.is_authenticated %}
                <li>User: {{ user.get_username }}</li>
                <li><a href="{% url 'logout'%}?next={{request.path}}">Logout</a></li>
                {% else %}
                <li><a href="{% url 'login'%}?next={{request.path}}">Login</a></li>
                {% endif %}
            </ul>
            {% endblock %}
        </div>
        <div class="col-sm-10 ">
        </div>
    </div>
    <div id="subheader">
        <div class="cart">
            Your cart is empty.
        </div>
    </div>
    <div id="content">
        <main class="container">

            {% block content %}
            {% endblock %}


        </main>
    </div>
</body>
</html>

catalog/templates/catalog/product/detail.html
{% extends "catalog/base.html" %}
{% load static %}

{% block title %}
{% if category %}{{ category.name }}{% else %}Products{% endif %}
{% endblock %}

{% block content %}
<div class="product-detail">
    <img src="{% if product.image %}{{ product.image.url }}{% else %}{% static " img/no_image.png" %}{% endif %}"
    style="height:200px;width:200px;">
    <h1>{{ product.name }}</h1>
    <h2><a href="{{ product.category.get_absolute_url }}">{{ product.category }}</a></h2>
    <p class="price">Ksh {{ product.price_in_shillings }}</p>
    {{ product.description|linebreaks }}
</div>
{% endblock %}

catalog/templates/catalog/product/list.html
{% extends "catalog/base.html" %}
{% load static %}


{% block title %}
  {% if category %}{{ category.name }}{% else %}Products{% endif %}
{% endblock %}

{% block content %}
  <div id="sidebar">
    <h3>Categories</h3>
    <ul>
      <li {% if not category %}class="selected"{% endif %}>
        <a href="{% url "catalog:product_list" %}">All</a>
      </li>
      {% for c in categories %}
        <li {% if category.slug == c.slug %}class="selected"{% endif %}>
          <a href="{{ c.get_absolute_url }}">{{ c.name }}</a>
        </li>

      {% endfor %}

    </ul>
    <p>You have visited this page {{ visits }} time{% if visits > 1 %}s{% endif %}.</p>
  </div>
  <div id="main" class="product-list">
    <h1>{% if category %}{{ category.name }}{% else %}Products{% endif %}</h1>
    <div class="row">
    {% for product in products %}
        <div class="col">
            <div class="card" style="width: 18rem;">
                <img src="{% if product.image %}{{ product.image.url }}{% else %}{% static "img/no_image.png" %}
                {% endif %}" style="height:200px;width:200px;">
                <div class="card-body">
                    <h5 class="card-title">{{product.name}}</h5>
                    <p class="card-text">Ksh{{ product.price_in_shillings }}</p>
                       {{ product.description|linebreaks }}
                    <a href="#" class="btn btn-primary">Add to Cart</a>
                </div>
            </div>
        </div>
    {% endfor %}

  </div>
{% endblock %}